# Generated by Django 2.2.7 on 2019-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191030_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openSpots', models.IntegerField()),
                ('totalSpots', models.IntegerField()),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
