# Generated by Django 2.2.7 on 2019-12-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='masked',
            field=models.BooleanField(default=False),
        ),
    ]
