# Generated by Django 3.0.1 on 2019-12-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image_masked'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cameraId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='cameraId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
