# Generated by Django 3.0.1 on 2019-12-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191218_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cameraId',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='cameraId',
        ),
    ]
