# Generated by Django 3.0.1 on 2019-12-18 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191218_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='openSpotsList',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='takenSpotsList',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
